version: "3"
services:

  #启动注册中心eureka-server集群 集中管理/服务注册/服务发现
  discovery1:
    image: 120.79.73.92:5000/billjiang/discovery
    ports:
      - "8761:8761"
    networks:
      - webnet
    environment:
      - ADDITIONAL_EUREKA_SERVER_LIST=http://discovery2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8761

  discovery2:
    image: 120.79.73.92:5000/billjiang/discovery
    ports:
      - "8762:8762"
    environment:
      - ADDITIONAL_EUREKA_SERVER_LIST=http://discovery1:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8762
    networks:
      - webnet

  #启动配置中心config-server集群 配置更新/配置集中管理/多环境配置
  config1:
    image: 120.79.73.92:5000/billjiang/configserver
    ports:
      - "8090:8090"
    environment:
      - EUREKA_SERVER_LIST=http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8090
    networks:
      - webnet

  config2:
    image: 120.79.73.92:5000/billjiang/configserver
    ports:
      - "8091:8091"
    environment:
      - EUREKA_SERVER_LIST=http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8091
    networks:
      - webnet

  #启动网关gateway,可配置成集群,使用nginx进行负载 智能路由/安全控制/负载均衡
  gateway:
    image: 120.79.73.92:5000/billjiang/gateway
    ports:
      - "8086:8086"
    environment:
      - EUREKA_SERVER_LIST=http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8086
    networks:
      - webnet


  # 启动seluth+zipkin zipkin服务跟踪/依赖可视化
  track:
    image: 120.79.73.92:5000/billjiang/track
    ports:
      - "9411:9411"
    environment:
      - EUREKA_SERVER_LIST=http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9411
    networks:
      - webnet


   # hystrix
  # 启动hystrix-dashboard
  hystrix-dashboard:
    image: 120.79.73.92:5000/billjiang/hystrix-dashboard
    ports:
      - "8087:8087"
    environment:
      - EUREKA_SERVER_LIST=http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8087
    networks:
      - webnet

  # 启动hystrix-turbine-mq  基于消息中间件的实时性能数据收集
  hystrix-turbine-mq:
    image: 120.79.73.92:5000/billjiang/hystrix-turbine-mq
    ports:
      - "8089:8089"
    environment:
      - EUREKA_SERVER_LIST=http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8089
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=foodb
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=passw0rd
    networks:
      - webnet
networks:
  webnet:
    driver: overlay


